# Runs linting related jobs.

name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: typos
      - run: make typos-check

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Fmt
        run: make format-check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: |
          rustup update --no-self-update stable
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Clippy
        run: make clippy

  toml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: make toml-check

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup update --no-self-update stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Build docs
        run: make doc

  unused_deps:
    name: check for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: machete
        uses: bnjbvr/cargo-machete@main
