# Runs test related jobs.

name: test

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -C debuginfo=0

jobs:
  test:
    name: test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable, nightly ]
        os: [ ubuntu, macos, windows ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Rustup
        run: |
          rustup update --no-self-update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Run tests
        run: cargo test --workspace

      - name: Run tests with parallel feature
        run: cargo test --workspace --features parallel

  test-avx2:
    name: test with AVX2 on ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Rustup
        run: rustup update --no-self-update stable

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Run tests with AVX2
        run: |
          RUSTFLAGS="$RUSTFLAGS -C target-feature=+avx2" cargo test --workspace
